version: '3.9'
services:

#BACK-END
  backend_node_productos:
    container_name: backend_node_productos
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - base_datos_mysql
    volumes:
      - .:/app
  
  #BD
  base_datos_mysql:
    container_name: base_datos_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root1
      MYSQL_DATABASE: bd_productos
    ports:
      - "3332:3306"
  
  #MYADMIN
  servicio_phpmyadmin:
    container_name: servicio_phpmyadmin
    image: phpmyadmin
    environment:
      PMA_HOST: base_datos_mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root1
    ports:
      - "8081:80"
    depends_on:
      - base_datos_mysql